import { WhaleWorld } from './world.js';
import { ModelAnnotations } from './annotations.js';
import { lessonFor, lessonChapters, providers, LessonPlayer, autoReview } from './lessons.js';
import { moduleDefinitions } from './assets.js';
import { NOTES, PRESETS, HIGHLIGHTS, noteNumber, src } from './home-content.js';

const REQUEST=['帮我看看采购单还缺什么，顺便把缺的补进去。','Check what’s missing from my shopping list, and add it.'];
const chapters=[
 {slug:'hello',tag:'01 / MEET THE BIG WHALE',title:['给模型配上\n手脚和记性。','Give a model\nhands and a memory.'],body:['DeepSeek Harness（DSH）包在模型外面：替模型调用工具，记下每一步，再把结果交还给你。在这里，它长成一头大肥鲸。','DeepSeek Harness (DSH) wraps around a model. It runs the tools the model asks for, records each step, and hands the result back. Here, it takes the shape of the Big Whale.'],aside:['不是海洋生物课。是 AI 的开箱现场。','Not marine biology. More of an AI unboxing.'],modules:[]},
 {slug:'plugins',notes:['seams'],tag:'02 / EVERYTHING IS A PLUGIN',title:['拆开看，\n全是插件。','Open it up.\nIt’s all plugins.'],body:['模型接口、工具、会话记录，连执行循环本身都是插件，由 Cordis 组装起来。只要接口不变，提供方就能换，比如把 DeepSeek 适配换成录制回放。','The model adapter, tools, session log and even the agent loop are plugins, assembled by Cordis. As long as the contract stays the same, the provider can change, say from the DeepSeek adapter to a recorded replay.'],aside:['外面一整头，里面按块装。','One whale outside, built from blocks inside.'],modules:['agent_loop','llm_core','session_spine','tool_registry','capability_seam']},
 {slug:'loop',notes:['turn', 'fs'],thread:['模型还没见过这两个文件，所以先要一次 read，再决定怎么改。','The model has not seen either file yet, so it asks for a read before deciding what to change.'],tag:'03 / ONE MORE STEP',title:['它先读，\n再动手。','It reads first.\nThen it acts.'],body:['DSH 收到你的话，整理好上下文，交给模型。模型要用工具，DSH 就去执行，把结果带回来，再问模型一次。一件事可能要这样往返好几轮。','DSH takes your request, prepares the context and sends it to the model. When the model asks for a tool, DSH runs it, brings the result back and asks again. One task can take several of these rounds.'],aside:['“快好了”不算进度，工具返回结果才算。','“Almost done” isn’t progress. A tool result is.'],modules:['agent_loop','llm_core','tool_registry','session_spine']},
 {slug:'tools',notes:['pipeline'],thread:['补写采购单要调用 edit。这次会话设为写入前先问你，所以它会停在气闸前等你点头。','Adding the items needs an edit call. This session asks before writes, so it waits at the airlock for your answer.'],tag:'04 / TOOLS, WITH BOUNDARIES',title:['要动手的事，\n可以先问你。','Before it acts,\nit can ask you.'],body:['使用方通过接口找提供方办事。每次工具调用都要先过策略检查和守卫，再执行，最后处理结果。策略要求确认时，你点了拒绝，工具本体就不会运行。','Consumers reach providers through a contract. Every tool call passes policy checks and guards before it runs, and its result is processed afterwards. If the policy asks for approval and you decline, the tool body does not run.'],aside:['机械臂再能干，也得在这道门前等你点头。','However capable the arm, it waits at this door for your answer.'],modules:['capability_seam','tool_registry','approval_airlock']},
 {slug:'install',notes:['manager', 'review', 'hmr'],look:1,tag:'05 / INSTALL, REMOVE',thread:['同一次 edit，这回换成装一个插件来审。','Same edit call. This time, a plugin reviews it.'],title:['装上它，\n用完再卸掉。','Install it.\nRemove it when you’re done.'],body:['能力可以按需增减。这里用插件页安装引导里的示例 Auto review：装好、选用后，写入前由当前模型先审一遍。它是实验功能，可能放过不安全的操作，也可能拦下有用的操作。随安装附带的可选组合包（比如 Agent Teams）只能开关，不能卸载。','Capabilities can be added and taken away. The example is Auto review, the one the plugin page’s install guide suggests: once installed and chosen, the current model reviews each write first. It is experimental and can allow unsafe actions or block useful ones. Optional bundles shipped with dsh, such as Agent Teams, can be switched off but not removed.'],aside:['装的时候大张旗鼓，卸的时候也不留尾巴。','Leaves no trace on the way out.'],modules:['cordis_workshop','approval_airlock']},
 {slug:'memory',notes:['session', 'compaction'],look:4,thread:['两次读取、你的批准、edit 的结果，都按顺序记在会话记录里。','Both reads, your approval, and the edit result are recorded in order in the session log.'],tag:'06 / PACK THE IMPORTANT BITS',title:['做过的每一步，\n都有记录。','Every step it took\nis on the record.'],body:['会话记录按顺序记下发生的每件事，模型看到的历史从这份记录里整理出来。上下文快满时，先裁掉过长的工具输出，再把较早的对话压成摘要。摘要可能漏掉线索，所以要留着回查原文的出处。','The session log records each event in order, and the history the model sees is built from it. When context runs short, long tool outputs are pruned first, then older turns are summarized. Summaries can miss clues, so keep a way back to the original.'],aside:['箱子可以压紧，证据别压丢了。','Pack it tight, but don’t pack away the evidence.'],modules:['session_spine','compaction_chamber']},
 {slug:'crew',notes:['subagent', 'presets'],look:5,thread:['这件事一个 Agent 就办完了。换成“把全家一年的账单分类汇总”，才值得派子 Agent。','One agent is enough for this request. Sorting a family’s year of bills is where subagents start to pay off.'],tag:'07 / THE CREW & THE WORKSHOP',title:['活太多，\n就分出去。','Too much work?\nHand some off.'],body:['子 Agent 接手有边界的子任务，后台作业处理耗时的活。预设决定一个会话默认带哪些能力，四种预设的区别见下方对照表。Creator 还能检查接口、通过插件管理器安装插件；装好以后，还得确认它真的生效。','Subagents take bounded subtasks, and background jobs handle long work. A preset decides which capabilities a session starts with; the table below compares the four. Creator can also inspect APIs and install plugins through Plugin Manager, and after installing you still check that the plugin is active.'],aside:['派出去的活，结果得交回来。','Work sent out has to report back.'],modules:['subagent_orca','cordis_workshop']},
 {slug:'cases',look:6,tag:'08 / LET’S DO SOMETHING',title:['现在，\n看它干活。','Now,\nwatch it work.'],body:['八个案例，从分账、审批照片到开一家像素风 AI 公司，每一步用了哪个组件、结果是什么，都摆在一起。','Eight cases, from splitting a bill and approving photos to running a pixel-art AI company, each showing which component acts at every step and what comes out.'],aside:['教学演示，不会让你的电脑偷偷加班。','Teaching demos. Your computer stays off the clock.'],modules:['agent_loop','tool_registry','subagent_orca','cordis_workshop']}
];

const LAST=chapters.length-1;
export class HomeExperience {
 constructor(){
   this.root=document.createElement('main');this.root.id='ocean-home';this.root.dataset.raw='';this.root.hidden=true;
   document.querySelector('#case-library').before(this.root);
   this.chapter=0;this.scrollPosition=0;this.active=false;this.exploring=false;this.abort=new AbortController();
   const signal=this.abort.signal;
   this.root.addEventListener('click',e=>{
     const note=e.target.closest('[data-note]');if(note){this.noteReturn=scrollY;const item=this.root.querySelector('#home-note-'+note.dataset.note);item.scrollIntoView({behavior:this.reduced()?'instant':'smooth',block:'center'});item.focus({preventScroll:true});return;}
     if(e.target.closest('[data-note-back]')){window.scrollTo({top:this.noteReturn??0,behavior:this.reduced()?'instant':'smooth'});return;}
     const jump=e.target.closest('[data-jump]');if(jump){this.jump(jump.dataset.jump);return;}
     const chapter=e.target.closest('[data-chapter]');if(chapter)this.go(Number(chapter.dataset.chapter));
     const mod=e.target.closest('[data-module]');if(mod)this.inspect(mod.dataset.module,mod.dataset.annotationKey);
     const action=e.target.closest('[data-lesson-action]');if(action){this.lessonAction(action.dataset.lessonAction,Number(action.dataset.step));return;}const provider=e.target.closest('[data-provider-choice]');if(provider){this.world?.lessonAction(null,null,Number(provider.dataset.providerChoice));this.root.querySelectorAll('[data-provider-choice]').forEach(b=>b.setAttribute('aria-pressed',String(b===provider)));return;}if(e.target.closest('[data-reduce]')){this.reducedMotion=!this.reduced();this.updateScroll();const b=this.root.querySelector('[data-reduce]');b.setAttribute('aria-pressed',String(this.reduced()));b.textContent=this.text(this.reduced()?['恢复动态','Motion on']:['减少动态','Less motion']);return;}if(e.target.closest('[data-explore]'))this.explore(!this.exploring);
   },{signal});
   this.root.addEventListener('input',e=>{const hull=e.target.closest('[data-hull-open]');if(hull){this.world?.setReveal(Number(hull.value)/100);return;}const scrub=e.target.closest('[data-lesson-scrub]');if(scrub)this.lessonAction('seek',Number(scrub.value));},{signal});
   window.addEventListener('scroll',()=>{if(!this.active||this.scrollFrame)return;this.scrollFrame=requestAnimationFrame(()=>{this.scrollFrame=null;this.updateScroll();});},{passive:true,signal});
   window.addEventListener('resize',()=>{this.measure();this.updateScroll();},{signal});
   window.addEventListener('dsh-preferences',()=>{if(this.active){const y=scrollY;this.render();window.scrollTo({top:y,behavior:'instant'});this.mountWorld();this.updateScroll();}},{signal});
   matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',()=>this.updateScroll(),{signal});
   document.addEventListener('keydown',e=>{if(this.active&&e.key==='Escape')this.explore(false);},{signal});
 }
 reduced(){return this.reducedMotion??matchMedia('(prefers-reduced-motion: reduce)').matches;}
 text(pair){return pair[window.DSHLocale?.language==='en'?1:0];}
 render(){
   this.world?.dispose();this.world=null;this.exploring=false;this.root.dataset.chapter='';this.root.classList.remove('exploring');
   const T=x=>this.text(x);
   const names=T([['初见','拆开','执行','工具','装卸','记忆','协作','开始'],['Meet','Inside','Loop','Tools','Install','Context','Crew','Begin']]);
   this.root.innerHTML=`
   <div class="ocean-stage"><div class="product-glow" aria-hidden="true"></div><canvas id="home-canvas" aria-hidden="true"></canvas><div class="model-annotations"></div><div class="home-loading" role="status">${T(['大肥鲸正在就位','Getting the Big Whale ready'])}<span></span></div></div>
   <nav class="local-nav" aria-label="${T(['本页导航','On this page'])}"><span class="local-title">${T(['大肥鲸 · DSH','Big Whale · DSH'])}</span><div class="local-links"><button data-jump="highlights">${T(['一分钟看懂','Highlights'])}</button><button data-chapter="4">${T(['插件装卸','Plugins'])}</button><button data-jump="presets">${T(['预设对照','Presets'])}</button><button data-jump="notes">${T(['来源','Sources'])}</button><button class="local-cta" data-mode="library">${T(['看案例','Cases'])}</button></div></nav>
   <nav class="chapter-rail" aria-label="${T(['科普章节','Story chapters'])}">${chapters.map((c,i)=>`<button data-chapter="${i}" aria-label="${T(c.title).replace('\n',' ')}"><span>${names[i]}</span><i></i></button>`).join('')}</nav>
   <div class="ocean-tools"><span class="chapter-position">01 / ${String(chapters.length).padStart(2,'0')}</span><button data-reduce aria-pressed="${this.reduced()}">${T(this.reduced()?['恢复动态','Motion on']:['减少动态','Less motion'])}</button><button data-explore aria-pressed="false">${T(['近距离看看','Take a closer look'])}<span aria-hidden="true">＋</span></button></div>
   ${chapters.map((c,i)=>`<section id="chapter-${c.slug}" class="ocean-chapter chapter-${c.look??i}" data-chapter-index="${i}"><div class="chapter-sticky"><div class="chapter-copy">
     <p class="ocean-eyebrow">${i===0?'DeepSeek Harness':T([['','模块化设计','执行循环','工具与审批','插件装卸','上下文管理','分工与扩展','八个案例'][i],['','Modular by design','The agent loop','Tools & approval','Plugin lifecycle','Context','Delegation','Eight cases'][i]])}</p>
     <${i===0?'h1':'h2'}>${T(c.title).split('\n').map((line,j)=>`<span class="headline-line line-${j}">${line}</span>`).join(window.DSHLocale?.language==='en'?' ':'')}</${i===0?'h1':'h2'}>${i===0?`<p class="hero-sub">${T(c.body)}</p>`:''}${c.thread?`<p class="request-thread"><span>${T(['你的请求','Your request'])}</span>${T(c.thread)}</p>`:''}
     <div class="chapter-detail">${i===0?this.requestMarkup():''}${lessonFor(i)?this.lessonMarkup(i):''}<div class="model-legend"></div>${i===0?'':`<p class="chapter-body">${T(c.body)}</p>`}${i===LAST?this.resultMarkup():''}
     ${i===0?`<div class="ocean-actions"><button class="dive-button" data-chapter="1">${T(['看看里面','Look inside'])} <span>↓</span></button><label class="hull-drag"><span>${T(['拖动，打开外壳','Drag to open the shell'])}</span><input type="range" min="0" max="100" value="0" data-hull-open></label><button class="quiet-link" data-mode="library">${T(['探索案例','View cases'])} ↗</button></div>`:''}
     ${c.modules.length?`<div class="module-chips">${c.modules.map(id=>{const d=moduleDefinitions.find(x=>x[0]===id);return `<button data-module="${id}">${T([d[1],d[2]])}<span aria-hidden="true">＋</span></button>`;}).join('')}</div>`:''}
     ${i===LAST?`<button class="dive-button final-cta" data-mode="library">${T(['进入八个案例','Explore all eight cases'])}<span>↗</span></button>`:''}
     ${c.notes?`<p class="chapter-sources">${T(['来源','Sources'])}${c.notes.map(id=>`<button data-note="${noteNumber(id)}" aria-label="${T(['注释','Note'])} ${noteNumber(id)}">${noteNumber(id)}</button>`).join('')}</p>`:''}
     <p class="whale-aside">${T(c.aside)}</p></div>
   </div>${i===0?this.highlightsMarkup():''}<span class="scene-caption" aria-hidden="true">${i===0?T(['向下滚动，打开新视角','Scroll to see a different side']):String(i+1).padStart(2,'0')+' / '+c.tag.split(' / ')[1]}</span></div></section>`).join('')}
   ${this.presetMarkup()}
   <section class="company-feature"><div class="company-feature-copy"><p class="ocean-eyebrow">${T(['第八个案例','Case eight'])}</p><h2>${T(['今天，<br>大肥鲸当老板。','Today, the whale<br>starts a company.'])}</h2><p>${T(['给 DSH 装一间像素风办公室：设计、开发、测试各有工位，第一单是做一个能用的番茄钟。','Install a pixel-art office into DSH, with desks for design, development and testing. The first order is a working Pomodoro timer.'])}</p><button class="dive-button" data-open-case="pixel-company">${T(['去公司看看','Visit the office'])}<span>↗</span></button></div><button class="company-feature-art" data-open-case="pixel-company" aria-label="${T(['进入像素公司案例','Open the pixel company case'])}"><img src="assets/pixel-office.png" alt="${T(['为教学生成的像素办公室示例','Generated pixel office for this teaching example'])}" loading="lazy"></button></section>
   ${this.notesMarkup()}
   <footer class="ocean-footer"><span>DSH INSIDE</span><p>${T(['独立社区科普。大肥鲸是社区对 DeepSeek logo 的昵称。空间布局为教学隐喻，动画不代表实时运行。','An independent community guide. Big Whale is a nickname for the DeepSeek logo. Spatial layouts are teaching metaphors; animations are not live runtime evidence.'])}</p><button id="home-sources">${T(['来源与版本','Sources & version'])} ↗</button></footer>
   <dialog class="module-dialog" id="module-dialog"><div></div><button class="dialog-close">${T(['关闭','Close'])} ×</button></dialog>`;
   this.annotations=new ModelAnnotations(this.root.querySelector('.model-annotations'),x=>this.text(x));this.measure();
   this.root.querySelector('#home-sources').onclick=()=>document.querySelector('#about').click();
   const dialog=this.root.querySelector('dialog');dialog.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
 }
 mountWorld(){
   if(!this.active)return;this.world?.dispose();
   const unavailable=()=>{const stage=this.root.querySelector('.ocean-stage');stage.classList.add('model-unavailable');const status=this.root.querySelector('.home-loading');status.hidden=false;status.textContent=this.text(['模型暂不可用，仍可阅读全部章节。','Model unavailable. All chapters are still readable.']);};
   try{this.world=new WhaleWorld(this.root.querySelector('canvas'),{home:true,onSelect:id=>this.inspect(id),onLoad:id=>{if(id==='orca_hull'){this.root.querySelector('.home-loading').hidden=true;this.root.querySelector('.ocean-stage').classList.add('loaded');}},onError:unavailable});this.world.onFrame=(time,frame)=>this.onFrame(frame);this.updateScroll();}catch{unavailable();this.root.querySelectorAll('[data-lesson-action="toggle"]').forEach(b=>{b.disabled=true;b.textContent=this.text(['逐步阅读','Step through']);});}
 }
 show(value){
   if(value===this.active)return;
   const q=new URLSearchParams(location.hash.slice(1)),savedY=this.scrollPosition;
   this.active=value;this.root.hidden=!value;
   if(value){this.render();if(q.get('view')==='home'&&q.has('chapter'))this.go(Number(q.get('chapter')),false);else window.scrollTo({top:savedY,behavior:'instant'});this.mountWorld();this.updateScroll();}
   else{cancelAnimationFrame(this.scrollFrame);this.scrollFrame=null;this.world?.dispose();this.world=null;this.exploring=false;}
 }
 go(index,smoothScroll=true){
   index=Math.max(0,Math.min(LAST,Number.isFinite(index)?index:0));
   const section=this.root.querySelector(`[data-chapter-index="${index}"]`);
   if(section)window.scrollTo({top:section.getBoundingClientRect().top+scrollY-document.querySelector('.header').offsetHeight,behavior:smoothScroll&&!this.reduced()?'smooth':'instant'});
 }
 jump(target){if(target==='highlights'){const s=this.layout?.sections[0];if(s)window.scrollTo({top:this.layout.origin-this.layout.header+s.top+s.height*.5,behavior:this.reduced()?'instant':'smooth'});return;}const el=this.root.querySelector('#home-'+target);if(el)window.scrollTo({top:el.getBoundingClientRect().top+scrollY-this.layout.header-48,behavior:this.reduced()?'instant':'smooth'});}
 measure(){if(!this.active)return;const sections=[...this.root.querySelectorAll('.ocean-chapter')];this.layout={header:document.querySelector('.header').offsetHeight,origin:this.root.getBoundingClientRect().top+scrollY,sections:sections.map(s=>({element:s,top:s.offsetTop,height:s.offsetHeight,copy:s.querySelector('.chapter-copy')}))};this.rail=[...this.root.querySelectorAll('.chapter-rail button')];this.stage=this.root.querySelector('.ocean-stage');this.oceanTools=this.root.querySelector('.ocean-tools');this.localNav=this.root.querySelector('.local-nav');this.railRoot=this.root.querySelector('.chapter-rail');const h1=this.root.querySelector('.chapter-0 h1');if(h1)this.root.style.setProperty('--hero-sub-top',`${h1.offsetTop+h1.offsetHeight+14}px`);this.highlights=this.root.querySelector('.hero-highlights');}
 updateScroll(){
   if(!this.active||!this.layout?.sections.length)return;
   const {sections,header,origin}=this.layout;this.scrollPosition=scrollY;
   const y=Math.max(0,scrollY-origin+header);let index=0;sections.forEach((s,i)=>{if(s.top<=y+1)index=i;});
   const section=sections[index],progress=Math.max(0,Math.min(1,(y-section.top)/section.height));
   const changed=this.chapter!==index;this.chapter=index;const reduced=this.reduced();this.root.dataset.reduced=String(reduced);
   const afterStory=Math.max(0,(y-sections[LAST].top-sections[LAST].height+innerHeight)/innerHeight);
   this.world?.setState({chapter:index,progress,theme:window.DSHLocale.theme,visible:afterStory<1.1,reduced});
   this.stage.style.opacity=String(1-Math.min(1,afterStory));this.oceanTools.style.visibility=afterStory>.7?'hidden':'visible';this.railRoot.style.visibility=afterStory>.7?'hidden':'visible';
   // The hero hands over to the highlights before the camera leaves chapter 1.
   const clamp=x=>Math.max(0,Math.min(1,x)),hero=(y-sections[0].top)/sections[0].height,cards=reduced?(index===0&&hero>=.36?1:0):clamp((hero-.36)/.08)*(1-clamp((hero-.60)/.08));
   this.highlights.style.opacity=String(cards);this.highlights.style.visibility=cards<.01?'hidden':'visible';this.localNav.classList.toggle('shown',hero>.3);
   sections.forEach((s,i)=>{const local=(y-s.top)/s.height;const enter=i===0?1:clamp((local+.12)/.12);const exit=i===0?1-clamp((local-.28)/.08):1-clamp((local-.66)/.20);const opacity=reduced?(i===index&&!(i===0&&cards)?1:0):enter*exit;s.copy.style.opacity=String(opacity);s.copy.style.visibility=opacity<.01?'hidden':'visible';s.copy.style.setProperty('--copy-shift',reduced?'0px':`${(1-enter)*24-(1-exit)*24}px`);});
   if(changed||this.root.dataset.chapter!==String(index)){
     this.root.dataset.chapter=String(index);this.rail.forEach((b,i)=>{b.classList.toggle('current',i===index);b.setAttribute('aria-current',i===index?'step':'false');});this.root.querySelector('.chapter-position').textContent=`${String(index+1).padStart(2,'0')} / ${String(chapters.length).padStart(2,'0')}`;
     history.replaceState(null,'',`#view=home&chapter=${index}`);
   }
 }
 highlightsMarkup(){const T=x=>this.text(x);return `<div class="hero-highlights" id="home-highlights"><h2>${T(['一分钟看懂','The highlights'])}</h2><ol>${HIGHLIGHTS.map((h,i)=>`<li><button data-chapter="${h.chapter}"><span class="highlight-index">${String(i+1).padStart(2,'0')}</span><strong>${T(h.title)}</strong><span>${T(h.body)}</span><em>${T(['看这一章','Go to chapter'])} →</em></button></li>`).join('')}</ol></div>`;}
 presetMarkup(){const T=x=>this.text(x),cell=v=>v===1?`<td><span class="yes" aria-label="${T(['有','Yes'])}">●</span></td>`:v===0?`<td><span class="no" aria-label="${T(['无','No'])}">—</span></td>`:`<td>${T(v)}</td>`;
   return `<section class="preset-compare" id="home-presets"><p class="ocean-eyebrow">${T(['预设对照','Compare presets'])}</p><h2>${T(['同一个 Harness，<br>四种出厂组合。','One harness.<br>Four starting kits.'])}</h2><p class="preset-lead">${T(['预设决定一个会话默认带哪些插件。Standard 是默认预设；Creator 在有 profile 时带上插件管理器工具。','A preset decides which plugins a session starts with. Standard is the default; Creator adds the Plugin Manager tool when a profile is present.'])}</p><div class="preset-scroll"><table><thead><tr><th scope="col"><span class="visually-hidden">${T(['能力','Capability'])}</span></th>${['Minimal','Standard','PTC','Creator'].map(n=>`<th scope="col">${n}</th>`).join('')}</tr></thead><tbody>${PRESETS.map(([name,...v])=>`<tr><th scope="row">${T(name)}</th>${v.map(cell).join('')}</tr>`).join('')}</tbody></table></div><p class="preset-foot">${T(['按 dsh 0.1.7-alpha.2 的 web-app 组合包整理；你的 profile 可以再覆盖这些设置。','From the web-app bundle in dsh 0.1.7-alpha.2; your profile can override these rows.'])}<button data-note="${noteNumber('presets')}" aria-label="${T(['注释','Note'])} ${noteNumber('presets')}">${noteNumber('presets')}</button></p></section>`;}
 notesMarkup(){const T=x=>this.text(x);return `<section class="home-notes" id="home-notes"><h2>${T(['注释与来源','Notes & sources'])}</h2><ol>${NOTES.map((n,i)=>`<li id="home-note-${i+1}" tabindex="-1"><span>${T(n.text)}</span> <a href="${src(n.path,n.lines)}" target="_blank" rel="noopener noreferrer">${n.path}${n.lines?':'+n.lines:''} ↗</a> <button class="note-back" data-note-back>${T(['返回正文','Back'])} ↩</button></li>`).join('')}</ol><p>${T(['以上链接锁定 DeepSeek Harness 提交 0010283（0.1.7-alpha.2，2026-09-23 核对）。八个案例仍按 ddefc45 核验，见“来源与版本”。','Links are pinned to DeepSeek Harness commit 0010283 (0.1.7-alpha.2, checked 2026-09-23). The eight cases are still checked against ddefc45; see Sources & version.'])}</p></section>`;}
 requestMarkup(){const T=x=>this.text(x);return `<figure class="request-bubble"><figcaption>${T(['跟着这一句话往下看','Follow this one request'])}</figcaption><p><span class="request-files" aria-label="${T(['附带文件','Attached files'])}">${T(['采购单.txt','shopping-list.txt'])} · ${T(['周末菜单.txt','weekend-menu.txt'])}</span>${T(REQUEST)}</p></figure>`;}
 resultMarkup(){const T=x=>this.text(x);return `<figure class="request-result"><figcaption>${T(['这句话最后的结果','Where the request ended up'])}</figcaption><p class="request-echo">${T(REQUEST)}</p><p class="request-reply">${T(['菜单要用番茄和鸡蛋，采购单上没有，已经补上了。','The menu needs tomatoes and eggs. They were missing from the list, so I added them.'])}</p><ol class="request-list">${T([['牛奶：2 盒','大米：1 袋','<ins>番茄：4 个</ins>','<ins>鸡蛋：6 个</ins>'],['Milk: 2 cartons','Rice: 1 bag','<ins>Tomatoes: 4</ins>','<ins>Eggs: 6</ins>']]).map(x=>`<li>${x}</li>`).join('')}</ol><small>${T(['教学示例：文件内容和回复都是为本页编写的，不是模型实际输出。','Teaching example: the files and reply were written for this page, not produced by a model.'])}</small></figure>`;}
 lessonMarkup(chapter){const T=x=>this.text(x),steps=lessonFor(chapter);return `<div class="lesson-panel" data-lesson="${chapter}"><p class="lesson-heading">${T(chapter===4?['把插件装上，再卸下','Install a plugin, then remove it']:['跟着模型，看一次完整过程','Follow one complete process'])}<span>${T(['教学演示','Teaching demo'])}</span></p>${chapter===4?`<p class="lesson-package"><code>${autoReview}</code><span>${T(['实验功能','Experimental'])}</span></p><input class="lesson-scrub" type="range" min="0" max="${steps.length-1}" step="1" value="0" data-lesson-scrub aria-label="${T(['拖动：从查看包到移除','Drag from inspect to remove'])}" aria-valuetext="${T([steps[0][0],steps[0][1]])}">`:''}${chapter===1?`<div class="provider-choices" aria-label="${T(['选择替换提供方','Choose a replacement provider'])}">${providers.map((p,i)=>`<button data-provider-choice="${i}" aria-pressed="${i===1}">${p.id}</button>`).join('')}</div>`:''}<div class="lesson-steps">${steps.map((s,i)=>`<button data-lesson-action="seek" data-step="${i}" aria-label="${T([s[0],s[1]])}" title="${T([s[0],s[1]])}">${i+1}</button>`).join('')}</div><div class="lesson-current"><strong>${T([steps[0][0],steps[0][1]])}</strong><p>${T([steps[0][2],steps[0][3]])}</p></div>${chapter===4?`<p class="lesson-note">${T(['Auto review 可能放过不安全的操作，也可能拦下有用的操作，并额外消耗 token。随安装附带的可选组合包（比如 Agent Teams）只能开关，不能卸载。','Auto review can allow unsafe actions, block useful ones, and spend extra tokens. Optional bundles shipped with dsh, such as Agent Teams, can be switched off but not removed.'])}</p>`:''}<div class="lesson-controls"><button data-lesson-action="previous">${T(['上一步','Previous'])}</button><button data-lesson-action="toggle">${T(['暂停演示','Pause demo'])}</button><button data-lesson-action="next">${T(['下一步','Next'])}</button></div></div>`;}
 lessonAction(action,step){if(this.world){this.world.lessonAction(action,step);return;}this.fallbackPlayers??=Object.fromEntries(lessonChapters.map(c=>[c,new LessonPlayer(c)]));const player=this.fallbackPlayers[this.chapter];if(!player)return;if(action==='seek')player.seek(step);else if(action==='next')player.seek(Math.floor(player.position)+1);else if(action==='previous')player.seek(Math.floor(player.position)-1);this.updateLesson(this.chapter,Math.floor(player.position),false);}
 updateLesson(chapter,step,playing){const panel=this.root.querySelector(`[data-lesson="${chapter}"]`);if(!panel)return;const key=step+':'+playing+':'+this.reduced()+':'+window.DSHLocale.language;if(panel.dataset.state===key)return;panel.dataset.state=key;const s=lessonFor(chapter)[step];panel.querySelector('.lesson-current strong').textContent=this.text([s[0],s[1]]);panel.querySelector('.lesson-current p').textContent=this.text([s[2],s[3]]);const toggle=panel.querySelector('[data-lesson-action="toggle"]');toggle.disabled=this.reduced()||!this.world;toggle.textContent=this.text(toggle.disabled?['逐步阅读','Step through']:playing?['暂停演示','Pause demo']:['播放演示','Play demo']);const scrub=panel.querySelector('[data-lesson-scrub]');if(scrub){scrub.value=String(step);scrub.setAttribute('aria-valuetext',this.text([s[0],s[1]]));}panel.querySelectorAll('.lesson-steps button').forEach((b,i)=>{b.classList.toggle('current',i===step);b.setAttribute('aria-current',i===step?'step':'false');});}
 onFrame(frame){if(!frame||!this.active)return;if(!this.exploring)this.annotations.update(this.world,frame.anchors,frame.chapter);else this.annotations.clear();if(frame.lesson)this.updateLesson(frame.chapter,frame.lesson.step,frame.playing);}

 explore(value){
   if(!this.world)return;this.exploring=value;this.world.setExplore(value);this.root.classList.toggle('exploring',value);
   const button=this.root.querySelector('[data-explore]');button.setAttribute('aria-pressed',String(value));button.innerHTML=this.text(value?['返回阅读 <span>×</span>','Back to reading <span>×</span>']:['近距离看看 <span>＋</span>','Take a closer look <span>＋</span>']);
 }
 inspect(id,key){
   const anchor=key&&this.world?.annotationFrame?.anchors.find(a=>a.key===key);
   let d=moduleDefinitions.find(x=>x[0]===id);
   if(anchor){const role=anchor.role||key,isToken=role==='input'||role==='output';d=[id,...anchor.label,...(isToken?['这块模型代表用户消息，是教学用的输入或输出标记。','This model represents a user message: a teaching marker for input or output.']:anchor.note),role==='port'||role==='old'||role==='next'?['llm']:(d?.[5]||[])];}
   if(!d)return;
   const dialog=this.root.querySelector('dialog'),title=document.createElement('h2');title.textContent=this.text([d[1],d[2]]);
   const p=document.createElement('p');p.textContent=this.text([d[3],d[4]]);
   const code=document.createElement('p');code.textContent=d[5].map(id=>'ctx.'+id).join(' / ');
   const note=document.createElement('p');note.textContent=this.text(['模型是功能的教学隐喻；实际调用取决于预设、配置和任务。','This model is a teaching metaphor. Actual calls depend on the preset, configuration, and task.']);
   const a=document.createElement('a');a.href=`https://github.com/deepseek-ai/deepseek-harness/blob/${window.DSHInside.catalog.meta.commit}/docs/architecture.md`;a.target='_blank';a.rel='noopener noreferrer';a.textContent=this.text(['查看官方架构说明 ↗','Official architecture ↗']);
   dialog.firstElementChild.replaceChildren(title,p,code,note,a);dialog.showModal();
 }
}
