/* Learning paths and preset comparison, original UI. No external dependencies. */
(() => {
 'use strict';
 const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const T=s=>window.DSHLocale.t(s);
 const H=s=>E(T(s));
 const meta=JSON.parse(document.getElementById('catalog-data').textContent);const SHA='46a7f68b0922371ce7144b668b90e377d8e799f4';
 const presets=JSON.parse(document.getElementById('modes-data').textContent);
 const source=p=>`https://github.com/deepseek-ai/deepseek-harness/blob/${SHA}/${p}`;
 const icon=id=>window.DSHIdentity.svg(id);
 const preset=id=>presets.find(m=>m.id===id)||presets[1];
 function miniModes(){return `<div class="mode-mini-grid">${presets.map(m=>`<button data-open-preset="${m.id}" class="mode-mini" style="--preset-color:${m.color}"><span class="mode-symbol">${icon(m.glyph)}</span><span><b>${H(m.name)}</b><small>${H(m.title)}</small></span><span class="tiny-next">↗</span></button>`).join('')}</div>`;}
 function library(cases,filter='all'){
   const list=filter==='all'?cases:cases.filter(s=>s.preset===filter);
   return `<div class="library-wrap"><section class="library-hero"><div class="hero-copy"><span class="eyebrow">DEEPSEEK HARNESS / FIELD NOTES</span><h1>${H('六件要做完的事。')}<em>${H('大肥鲸一件件拆给你看。')}</em></h1><p>${H('修好网站、整理文件、交付数据、调查故障。看大肥鲸怎样动手，遇到问题怎样调整，又凭什么说完成了。')}</p><div class="hero-actions"><button class="hero-start" data-open-case="repair-site">${H('第一次下水？从这里开始')} <span>↗</span></button><button data-mode="modes" class="hero-secondary">${H('先看四种模式')} →</button></div></div><div class="library-product" aria-hidden="true"><img data-product-asset="orca_hull" alt=""></div><div class="hero-modes"><div class="hero-modes-head"><span class="eyebrow">ONE HARNESS / FOUR PRESETS</span><span class="mode-live">4</span></div>${miniModes()}<p>${H('同一个模型，换一套预设，能用的工具就不一样。')}</p></div></section>
   <div class="curriculum-top"><div><span class="eyebrow">${H('学习路线')}</span><h2>${H('由易到难')}<span class="case-count">${String(cases.length).padStart(2,'0')}</span></h2></div><div class="curriculum-filters" role="group" aria-label="${H('推荐预设')}">${[['all','全部案例'],...presets.map(m=>[m.id,m.name])].map(([id,name])=>`<button data-case-filter="${id}" class="${filter===id?'selected':''}" aria-pressed="${filter===id}">${H(name)}</button>`).join('')}</div></div>
   <div class="case-grid">${list.map(s=>{const m=preset(s.preset);return `<article class="case-card" data-preset="${m.id}" data-company="${!!s.company}" style="--preset-color:${m.color}"><div class="case-card-top"><span class="case-number">${String(s.rank).padStart(2,'0')}</span><span class="level-pill">${H(s.difficulty)}</span><span class="preset-badge">${H(m.name)}</span></div><div class="case-art" aria-hidden="true">${s.company?'<img src="assets/pixel-office.png" alt="" loading="lazy">':`<img data-product-asset="${s.asset}" alt="">`}</div><h3>${H(s.name)}</h3><p class="case-story">${H(s.story)}</p><div class="case-learns"><span class="eyebrow">${H('你会看到')}</span><div>${s.features.map(f=>`<span>${H(f)}</span>`).join('')}</div></div><button class="case-open" data-open-case="${s.id}"><span>${H('跳进这个案例')}</span><span>↗</span></button></article>`;}).join('')||`<p>${H('暂无对应推荐案例。')}</p>`}</div>
   <div class="library-bottom"><p>${H('源码节选有出处；示例执行没有调用真实模型。')}</p><button data-mode="atlas">${meta.services.length} ${H('个服务')} · ${meta.services.filter(s=>s.role==='seam').length} seams ↗</button></div></div>`;
 }
 function modeCard(m,selected){return `<button class="preset-choice ${selected===m.id?'selected':''}" data-choose-preset="${m.id}" aria-pressed="${selected===m.id}" style="--preset-color:${m.color}"><div class="preset-card-head"><span class="mode-symbol">${icon(m.glyph)}</span><span class="preset-badge">${H(m.tag)}</span></div><h3>${H(m.name)}</h3><h4>${H(m.title)}</h4><p>${H(m.blurb)}</p><div class="model-visible"><span>${H('模型直接看到')}</span><code>${E(m.id==='minimal'?'bash / pwsh + editor':m.id==='standard'?'read · edit · bash · …':m.id==='ptc'?'run_code':'inspect + plugin_manager')}</code></div></button>`;}
 function modes(selected='standard'){
   const m=preset(selected),rows=['模型原生工具入口','系统提示词','上下文压缩','技能目录','子任务委派','workflow 工具','Creator 扩展工具'];
   return `<div class="modes-wrap"><div class="modes-heading"><span class="eyebrow">PRESET LAB / SOURCE-GROUNDED</span><h1>${H('四种预设，一眼看清能力组合的差别。')}</h1><p>${H('选择的是 Agent 预设。计划模式、审批策略和模型推理强度属于其他设置。')}</p></div><div class="preset-choice-grid">${presets.map(p=>modeCard(p,selected)).join('')}</div>
   <section class="preset-workshop" data-preset="${m.id}" style="--preset-color:${m.color}"><div class="workshop-main"><div class="workshop-heading"><span class="eyebrow">${H('按任务选择能力组合')}</span><span class="preset-badge">${H(m.name)}</span></div><h2>${H('工具组织不同，权限和运行条件仍需分别确认。')}</h2><p class="preset-use">${H(m.strengths)}</p><p class="comparison-caveat">${H('预设决定默认装配的能力。按任务所需选择，不必为了更多工具换预设；当前 Profile 还可以覆盖设置。')}</p><button class="hero-start" data-mode="library">${H('按任务看案例')} <span>↗</span></button></div><div class="workshop-details"><h4>${H('主要变化')}</h4><p>${H(m.delta)}</p><h4>${H('要注意')}</h4><p>${H(m.limits)}</p><details><summary>${H('配置摘录与流程标识')}</summary><pre data-raw>${E(m.snippet)}</pre></details><a href="${source(m.source)}" target="_blank" rel="noopener noreferrer">${H('查看预设原文件 ↗')}</a></div></section>
   <section class="mode-matrix"><div class="matrix-heading"><span class="eyebrow">${H('功能对照')}</span><p>${H('四种预设都由宿主提供模型、核心注册表和会话记录。具体权限取决于实际部署；工具数量不能代表权限强弱。')}</p></div><div class="matrix-scroll"><table><thead><tr><th scope="col">${H('观察重点')}</th>${presets.map(p=>`<th scope="col" class="${p.id===selected?'highlight':''}">${H(p.name)}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr><th scope="row">${H(r)}</th>${presets.map(p=>`<td class="${p.id===selected?'highlight':''} ${p.cells[i]==='未挂载'||p.cells[i]==='无委派工具'?'off':''}">${H(p.cells[i])}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section><div class="mode-footnotes"><p><b>${H('来源与边界')}</b><br>${H('这里切换的是预设说明，不改变任何真实会话。案例分别注明所需的能力和配置条件。')}</p><p>${H('这组对照固定到源码提交')} <code>${SHA.slice(0,7)}</code> · <a href="${source('packages/bundle/web-app/presets/'+(m.id==='cordis'?'cordis':m.id)+'.patch.yml')}" target="_blank" rel="noopener noreferrer">web-app presets ↗</a><br>${H('Creator 使用只读检查与 Plugin Manager 管理持久插件。')}</p></div></div>`;
 }
 window.DSHStudy={library,modes,presets,preset};
})();
