/* Learning paths and preset comparison, original UI. No external dependencies. */
(() => {
 'use strict';
 const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const T=s=>window.DSHLocale.t(s);
 const H=s=>E(T(s));
 const meta=JSON.parse(document.getElementById('catalog-data').textContent);const SHA=meta.meta.commit;
 const presets=JSON.parse(document.getElementById('modes-data').textContent);
 const source=p=>`https://github.com/deepseek-ai/deepseek-harness/blob/${SHA}/${p}`;
 const icon=id=>window.DSHIdentity.svg(id);
 const preset=id=>presets.find(m=>m.id===id)||presets[1];
 function miniModes(){return `<div class="mode-mini-grid">${presets.map(m=>`<button data-open-preset="${m.id}" class="mode-mini" style="--preset-color:${m.color}"><span class="mode-symbol">${icon(m.glyph)}</span><span><b>${H(m.name)}</b><small>${H(m.title)}</small></span><span class="tiny-next">↗</span></button>`).join('')}</div>`;}
 function library(cases,filter='all'){
   const list=filter==='all'?cases:cases.filter(s=>s.preset===filter);
   return `<div class="library-wrap"><section class="library-hero"><div class="hero-copy"><span class="eyebrow">DEEPSEEK HARNESS / FIELD NOTES</span><h1>${H('小事一桩。')}<em>${H('里面，大有文章。')}</em></h1><p>${H('八个生活案例，从一句需求，到一件做完的事。跟着大肥鲸，看看每一步怎么发生。')}</p><div class="hero-actions"><button class="hero-start" data-open-case="meet-dsh">${H('第一次来？从这里开始')} <span>↗</span></button><button data-mode="modes" class="hero-secondary">${H('先看四种模式')} →</button></div></div><div class="library-product" aria-hidden="true"><img data-product-asset="orca_hull" alt=""></div><div class="hero-modes"><div class="hero-modes-head"><span class="eyebrow">ONE HARNESS / FOUR PRESETS</span><span class="mode-live">4</span></div>${miniModes()}<p>${H('同一个模型，换一套预设，能力组合会怎样变化？')}</p></div></section>
   <div class="curriculum-top"><div><span class="eyebrow">${H('学习路线')}</span><h2>${H('由易到难')}<span class="case-count">08</span></h2></div><div class="curriculum-filters" role="group" aria-label="${H('推荐预设')}">${[['all','全部案例'],...presets.map(m=>[m.id,m.name])].map(([id,name])=>`<button data-case-filter="${id}" class="${filter===id?'selected':''}" aria-pressed="${filter===id}">${H(name)}</button>`).join('')}</div></div>
   <div class="case-grid">${list.map(s=>{const m=preset(s.preset);return `<article class="case-card" data-preset="${m.id}" data-company="${!!s.company}" style="--preset-color:${m.color}"><div class="case-card-top"><span class="case-number">${String(s.rank).padStart(2,'0')}</span><span class="level-pill">${H(s.difficulty)}</span><span class="preset-badge">${H(m.name)}</span></div><div class="case-art" aria-hidden="true">${s.company?'<img src="assets/pixel-office.png" alt="" loading="lazy">':`<img data-product-asset="${({'meet-dsh':'orca_hull',dinner:'shell_execution_bay',photos:'approval_airlock',shopping:'filesystem_bay',registration:'ptc_core','welcome-event':'subagent_orca',voyage:'compaction_chamber'})[s.id]}" alt="">`}</div><h3>${H(s.name)}</h3><p class="case-story">${H(s.story)}</p><div class="case-learns"><span class="eyebrow">${H('你会看到')}</span><div>${s.features.map(f=>`<span>${H(f)}</span>`).join('')}</div></div><button class="case-open" data-open-case="${s.id}"><span>${H('开始这个案例')}</span><span>↗</span></button></article>`;}).join('')||`<p>${H('暂无对应推荐案例。')}</p>`}</div>
   <div class="library-bottom"><p>${H('源码节选有出处；示例执行没有调用真实模型。')}</p><button data-mode="atlas">${meta.services.length} ${H('个服务')} · ${meta.services.filter(s=>s.role==='seam').length} seams ↗</button></div></div>`;
 }
 function modeCard(m,selected){return `<button class="preset-choice ${selected===m.id?'selected':''}" data-choose-preset="${m.id}" aria-pressed="${selected===m.id}" style="--preset-color:${m.color}"><div class="preset-card-head"><span class="mode-symbol">${icon(m.glyph)}</span><span class="preset-badge">${H(m.tag)}</span></div><h3>${H(m.name)}</h3><h4>${H(m.title)}</h4><p>${H(m.blurb)}</p><div class="model-visible"><span>${H('模型直接看到')}</span><code>${E(m.id==='minimal'?'bash / pwsh + editor':m.id==='standard'?'read · edit · bash · …':m.id==='ptc'?'run_code':'inspect + plugin_manager')}</code></div></button>`;}
 function modes(selected='standard'){
   const m=preset(selected),rows=['模型原生工具入口','系统提示词','上下文压缩','技能目录','子任务委派','workflow 工具','Creator 扩展工具'];
   return `<div class="modes-wrap"><div class="modes-heading"><span class="eyebrow">PRESET LAB / SOURCE-GROUNDED</span><h1>${H('四种预设，一眼看清能力组合的差别。')}</h1><p>${H('选择的是 Agent 预设。计划模式、审批策略和模型推理强度属于其他设置。')}</p></div><div class="preset-choice-grid">${presets.map(p=>modeCard(p,selected)).join('')}</div>
   <section class="preset-workshop" data-preset="${m.id}" style="--preset-color:${m.color}"><div class="workshop-main"><div class="workshop-heading"><span class="eyebrow">${H('同一顿饭，四种做法')}</span><span class="preset-badge">${H(m.name)}</span></div><h2>${H('相同输入：96、54、30 元，三人平摊。相同目标：转账 6 元和 30 元给安安。')}</h2><div class="comparison-route">${T(m.route).split(' → ').map((x,i)=>`<div class="route-stop"><span>${i+1}</span><b>${E(x)}</b></div>`).join('<i aria-hidden="true">→</i>')}</div><p class="comparison-caveat">${H('这里比较工具组织方式，不对模型能力排序。流程阶段用于教学说明，不能用来推算真实调用次数或性能。')}</p><button class="hero-start" data-demo-preset="${m.id}">${H('进入任务导览')} <span>↗</span></button></div><div class="workshop-details"><h4>${H('主要变化')}</h4><p>${H(m.delta)}</p><h4>${H('要注意')}</h4><p>${H(m.limits)}</p><details><summary>${H('配置摘录与流程标识')}</summary><pre data-raw>${E(m.snippet)}</pre></details><a href="${source(m.source)}" target="_blank" rel="noopener noreferrer">${H('查看预设原文件 ↗')}</a></div></section>
   <section class="mode-matrix"><div class="matrix-heading"><span class="eyebrow">${H('功能对照')}</span><p>${H('四种预设都由宿主提供模型、核心注册表和会话记录。具体权限取决于实际部署；工具数量不能代表权限强弱。')}</p></div><div class="matrix-scroll"><table><thead><tr><th scope="col">${H('观察重点')}</th>${presets.map(p=>`<th scope="col" class="${p.id===selected?'highlight':''}">${H(p.name)}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr><th scope="row">${H(r)}</th>${presets.map(p=>`<td class="${p.id===selected?'highlight':''} ${p.cells[i]==='未挂载'||p.cells[i]==='无委派工具'?'off':''}">${H(p.cells[i])}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section><div class="mode-footnotes"><p><b>${H('来源与边界')}</b><br>${H('真实会话一旦产生消息或工具调用，就不能直接切换预设。本页切换仅比较独立教学路径。')}</p><p>${H('这组对照固定到源码提交')} <code>${SHA.slice(0,7)}</code> · <a href="${source('packages/preset/agent-presets/README.md')}" target="_blank" rel="noopener noreferrer">agent-presets ↗</a><br>${H('Creator 使用只读检查与 Plugin Manager 管理持久插件。')}</p></div></div>`;
 }
 const cache={};
 function records(language='zh'){
   if(cache[language])return cache[language];const en=language==='en';
   const zhplaces=['北侧甲板','冷藏舱','二号观测室','淡水储备舱','动力隔间','西侧通道','通讯站','样本室','驾驶室','医疗舱','货舱门','轮值休息室'];
   const enplaces=['north deck','refrigerated hold','observation room two','freshwater reserve','engine compartment','west passage','communications station','sample room','bridge','medical bay','cargo door','crew lounge'];
   const zhtasks=['核对设备标签','清点封存样本','复查传感器读数','记录维护计划','检查备份通讯','确认交接记录','整理测绘片段','复核气象编号'];
   const entasks=['check equipment labels','count sealed samples','review sensor readings','log a maintenance plan','check backup communications','confirm a handover','organize mapping fragments','review weather IDs'];
   const needles={
    187:en?'Request D-17; cause: Begonia Port channel closure; proposed destination: Egret Port.':'申请编号 D-17；原因：海棠港航道封闭；拟改目的地：白鹭港。',
    674:en?'D-17 approved; authorizer: Lin Lan; approved destination: Egret Port.':'D-17 审批完成；批准人：林岚；批准目的地：白鹭港。',
    675:en?'Unrelated record R-17 approved; authorizer: Meng Zhou; destination: Bluestone Port. Do not merge with D-17.':'无关记录 R-17 已批准；批准人：孟舟；目的地：青石港。不得与 D-17 混同。',
    1109:en?'Execution confirmed: D-17 is effective; Farstar is proceeding to Egret Port.':'执行确认：D-17 已生效；远星号最终驶向白鹭港。'
   };
   cache[language]=Array.from({length:1200},(_,i)=>{
     const n=i+1,id=String(n).padStart(4,'0'),p=en?enplaces[n%12]:zhplaces[n%12],task=en?entasks[(n*7)%8]:zhtasks[(n*7)%8],batch=`Z-${String(100+(n*17)%899)}`;
     const ordinary=en?`Routine checklist ${batch} was completed. No destination change was authorized in this record.`:`例行清单 ${batch} 已完成。本条没有批准任何目的地变更。`;
     const text=en?
`Farstar Voyage Record #${id}\nDocument class: original teaching corpus; record ${n} of 1200.\nWork area: ${p}. Duty task: ${task}.\nShift ${1+Math.floor(i/24)}; index ${n%24}; sample batch ${batch}.\nThe crew checked ${3+n%19} numbered items and noted ${1+n%4} routine follow-ups. The reported reading ${17+(n%130)/10} is a fictional instrument value, not a performance metric.\n${needles[n]||ordinary}\nThe handover preserves this record's own identifier. Nearby records can describe unrelated ships or permissions; proximity does not establish a shared event.\nNavigation notes, weather summaries and maintenance checklists remain separately attributable. When a later summary is incomplete, use the record number to verify the original wording rather than filling the gap from another entry.\nReview: the document is a deterministic teaching fixture. All characters and incidents are fictional; no real vessel or operational advice is implied.`:
`远星号航行档案 #${id}\n资料性质：原创教学语料；第 ${n} 份，共 1200 份。\n工作区域：${p}。当班事项：${task}。\n轮值批次 ${1+Math.floor(i/24)}；序号 ${n%24}；样本批号 ${batch}。\n值班组核对了 ${3+n%19} 件带编号物品，登记 ${1+n%4} 项例行跟进。仪表读数 ${17+(n%130)/10} 为虚构背景，不表示任何真实设备性能。\n${needles[n]||ordinary}\n交接时保留本记录的独立编号。邻近档案可能记载另一艘船或另一项授权，不能因为位置接近就把它们合并成同一事件。\n航行备注、天气说明和维修清单分别保留来源。后续摘要若省略细节，应按记录编号查核原句，不从无关条目借用答案。\n核查说明：这是一份确定性生成的教学记录，人物与事件均为虚构，不涉及真实船舶或操作建议。`;
     return {id,n,title:en?`Record #${id} · ${p}`:`记录 #${id} · ${p}`,text,needle:!!needles[n]};
   });return cache[language];
 }
 function corpus(language='zh'){return records(language).map(r=>r.text).join('\n\n'+'─'.repeat(36)+'\n\n')+'\n';}
 function archiveShell(){const rs=records(window.DSHLocale.language),chars=corpus(window.DSHLocale.language).length;return `<div class="archive-head"><span class="eyebrow">${H('档案阅览室')}</span><button data-close aria-label="${H('关闭')}">×</button></div><h2>${H('1200 份原创航行记录')}</h2><p>${H('可查全文。这里在浏览器本地搜索原文，没有调用模型。')}</p><div class="archive-controls"><input id="archive-search" type="search" placeholder="${H('搜索编号、事件或关键词')}" aria-label="${H('搜索编号、事件或关键词')}"><button id="download-archive" class="outline-button">${H('下载当前语言全文')}</button></div><div class="archive-evidence"><span>${H('关键证据')}</span>${['0187','0674','0675','1109'].map(id=>`<button data-archive-q="${id}">#${id}</button>`).join('')}<button data-archive-q="">${H('清空搜索')}</button></div><p class="archive-count" id="archive-count">1,200 · ${chars.toLocaleString()} ${H('字 / characters')}</p><div id="archive-records"></div><div class="archive-pagination"><button id="archive-prev" class="outline-button">← ${H('上一页')}</button><span id="archive-page"></span><button id="archive-next" class="outline-button">${H('下一页')} →</button></div><p class="archive-note">${H('字符数不等于 Token 数。窗口压力为示意；没有执行模型容量评测。')}</p>`;}
 function learningNotes(){return `<h2>${H('源码与研究依据')}</h2><p>${H('阅读资料本身不会触发压缩。只有进入会话的内容和历史压力达到配置条件时，压缩后端才会介入。')}</p><p>${H('精确引用前回查原文；有损摘要无法承诺保留所有细节。')}</p><p>${H('研究提示：检索到一个词并不能证明长文理解；本例要求关联三条证据并排除一个干扰项。')}</p><div class="source-table">${[
 [source('packages/compaction/compaction-basic/README.md'),'DSH compaction-basic · pressure, pruning, summary, overflow'],
 ['https://arxiv.org/abs/2307.03172','Lost in the Middle (2023)'],['https://arxiv.org/abs/2404.06654','RULER (2024)'],
 [source('packages/preset/agent-presets/presets/minimal/agent.cordis.yml'),'Minimal · no compaction'],
 [source('packages/extensions/tool-cordis/README.md'),'Creator / Cordis · read-only inspection + Plugin Manager']].map(([u,t])=>`<a href="${u}" target="_blank" rel="noopener noreferrer">${E(t)} ↗</a>`).join('')}</div><p>${H('当前示例没有绑定真实模型；能力与限制来自固定的官方源码。')}</p>`;}
 window.DSHStudy={presets,preset,library,modes,records,corpus,archiveShell,learningNotes};
})();
